"""add schedule message table

Revision ID: bbb076a584a4
Revises: 952b34902a51
Create Date: 2025-05-16 15:15:10.446684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbb076a584a4'
down_revision: Union[str, None] = '952b34902a51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule_posts',
    sa.Column('schedule_id', sa.BigInteger(), nullable=False),
    sa.Column('target_type', sa.String(), nullable=False),
    sa.Column('scheduled_time', sa.DateTime(), nullable=False),
    sa.Column('data_json', sa.JSON(), nullable=True),
    sa.Column('post_message', sa.Text(), nullable=False),
    sa.Column('author_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.telegram_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('schedule_id'),
    sa.UniqueConstraint('schedule_id')
    )
    op.create_unique_constraint(None, 'bonuses', ['id'])
    op.add_column('customers', sa.Column('qr_code_file_id', sa.String(), nullable=True))
    op.add_column('customers', sa.Column('qr_code_token', sa.Integer(), nullable=True))
    op.add_column('customers', sa.Column('i_name', sa.String(), nullable=True))
    op.add_column('customers', sa.Column('i_surname', sa.String(), nullable=True))
    op.add_column('customers', sa.Column('email', sa.String(), nullable=True))
    op.add_column('customers', sa.Column('birthday', sa.String(length=10), nullable=True))
    op.drop_column('customers', 'bonus')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('bonus', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.drop_column('customers', 'birthday')
    op.drop_column('customers', 'email')
    op.drop_column('customers', 'i_surname')
    op.drop_column('customers', 'i_name')
    op.drop_column('customers', 'qr_code_token')
    op.drop_column('customers', 'qr_code_file_id')
    op.drop_constraint(None, 'bonuses', type_='unique')
    op.drop_table('schedule_posts')
    # ### end Alembic commands ###
