"""add table customers, schedule post, detail info

Revision ID: 05d22dce718b
Revises: 56eaebb0b9af
Create Date: 2025-05-16 19:49:03.037376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05d22dce718b'
down_revision: Union[str, None] = '56eaebb0b9af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('bonuses_id_key', 'bonuses', ['id'])
    op.add_column('customers', sa.Column('qr_code_file_id', sa.String(), nullable=True))
    op.add_column('customers', sa.Column('qr_code_token', sa.Integer(), nullable=True))
    op.add_column('customers', sa.Column('i_name', sa.String(), nullable=True))
    op.add_column('customers', sa.Column('i_surname', sa.String(), nullable=True))
    op.add_column('customers', sa.Column('email', sa.String(), nullable=True))
    op.add_column('customers', sa.Column('birthday', sa.String(length=10), nullable=True))
    op.create_unique_constraint('customers_telegram_id_key', 'customers', ['telegram_id'])
    op.drop_column('customers', 'bonus')
    op.create_unique_constraint('schedule_posts_schedule_id_key', 'schedule_posts', ['schedule_id'])
    op.create_unique_constraint('users_telegram_id_key', 'users', ['telegram_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_telegram_id_key', 'users', type_='unique')
    op.drop_constraint('schedule_posts_schedule_id_key', 'schedule_posts', type_='unique')
    op.add_column('customers', sa.Column('bonus', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.drop_constraint('customers_telegram_id_key', 'customers', type_='unique')
    op.drop_column('customers', 'birthday')
    op.drop_column('customers', 'email')
    op.drop_column('customers', 'i_surname')
    op.drop_column('customers', 'i_name')
    op.drop_column('customers', 'qr_code_token')
    op.drop_column('customers', 'qr_code_file_id')
    op.drop_constraint('bonuses_id_key', 'bonuses', type_='unique')
    # ### end Alembic commands ###
