version: '3.8'
services:
  nats:
    image: nats:2.10
    entrypoint: /nats-server # Команда запуска внутри контейнера
    command: "-c /config/server.conf"
    ports:
      - "4222:4222"  # Основной порт для взаимодействия с сервером
      - "8222:8222"  # Порт для мониторинга сервера по HTTP (понадобится позже)
    volumes:
      - ./nats/data:/data  # Путь, по которому NATS-сервер будет хранить данные вне контейнера
      - ./nats/config/server.conf:/config/server.conf
  
  nats-ui:
    image: ghcr.io/nats-nui/nui:latest
    container_name: nats-nui
    ports:
      - "31311:31311" # Порты для доступа к NATS NUI
    volumes:
      - ./nui/db:/db
    depends_on:
      - nats

  redis:
    image: redis:7.4.2
    command: 
      - redis-server
    restart: on-failure
    ports:
      - "6379:6379"

  postgres:
    image: postgres:15-alpine
    restart: "no"  # избавляемся от автоматической перезагрузки
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      # Superuser username/password
      POSTGRES_USER: superuser
      POSTGRES_PASSWORD: superpassword
      POSTGRES_DB: data
    volumes:
      - "01-simple-alchemy-postgres:/var/lib/postgresql/data"

  pgadmin:
    image: dpage/pgadmin4:9
    restart: "no"
    ports:
      - "127.0.0.1:8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: inactive0073@gmail.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin
    volumes:
      - "01-simple-alchemy-pgadmin:/var/lib/pgadmin"
    depends_on:
      - postgres

volumes:
  01-simple-alchemy-pgadmin:
  01-simple-alchemy-postgres: