"""add timezone column, add timezone offset column

Revision ID: 53bc266aa1c9
Revises: d2d54b5528b8
Create Date: 2025-04-21 10:15:14.197251

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "53bc266aa1c9"
down_revision: Union[str, None] = "d2d54b5528b8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "timezone_offset",
            sa.SmallInteger(),
            nullable=True,
            comment="Сдвиг таймзоны",
        ),
    )
    op.add_column("users", sa.Column("timezone", sa.String(), nullable=True))
    op.drop_column("users", "utc")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "utc",
            sa.SMALLINT(),
            autoincrement=False,
            nullable=True,
            comment="Сдвиг таймзоны",
        ),
    )
    op.drop_column("users", "timezone")
    op.drop_column("users", "timezone_offset")
    # ### end Alembic commands ###
