"""added_caption_column_to_tgchannel

Revision ID: ead705d207f5
Revises: 175ef0908df1
Create Date: 2025-03-19 12:32:05.772783

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ead705d207f5"
down_revision: Union[str, None] = "175ef0908df1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("channels", sa.Column("channel_caption", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("channels", "channel_caption")
    # ### end Alembic commands ###
