"""change utc type ton smallint

Revision ID: d2d54b5528b8
Revises: 77087ea3433f
Create Date: 2025-04-21 09:48:21.660940

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d2d54b5528b8"
down_revision: Union[str, None] = "77087ea3433f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "utc",
        existing_type=sa.VARCHAR(length=50),
        type_=sa.SmallInteger(),
        comment="Сдвиг таймзоны",
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "utc",
        existing_type=sa.SmallInteger(),
        type_=sa.VARCHAR(length=50),
        comment=None,
        existing_comment="Сдвиг таймзоны",
        existing_nullable=True,
    )
    # ### end Alembic commands ###
