"""add new table customer

Revision ID: 605c869c6f1b
Revises: 5d8402fda7f0
Create Date: 2025-04-22 12:25:29.413559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '605c869c6f1b'
down_revision: Union[str, None] = '5d8402fda7f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('gender', sa.String(length=1), nullable=True),
    sa.Column('bonus', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('percent_cashback', sa.SmallInteger(), server_default=sa.text('3'), nullable=False),
    sa.Column('visits_per_year', sa.SmallInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('visits', sa.SmallInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('phone', sa.String(length=18), nullable=True),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('telegram_id'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('telegram_id')
    )
    op.add_column('users', sa.Column('role', sa.String(), server_default=sa.text("'guest'"), nullable=True))
    op.alter_column('users', 'timezone_offset',
               existing_type=sa.SMALLINT(),
               comment=None,
               existing_comment='Сдвиг таймзоны',
               existing_nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'timezone_offset',
               existing_type=sa.SMALLINT(),
               comment='Сдвиг таймзоны',
               existing_nullable=True)
    op.drop_column('users', 'role')
    op.drop_table('customers')
    # ### end Alembic commands ###
