"""add_channel_username_column

Revision ID: 175ef0908df1
Revises: d4621d03e8ee
Create Date: 2025-03-14 11:05:47.337469

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "175ef0908df1"
down_revision: Union[str, None] = "d4621d03e8ee"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "channels", sa.Column("channel_username", sa.String(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("channels", "channel_username")
    # ### end Alembic commands ###
