"""Added_auto_caption_column_to_TgChannel

Revision ID: 68ceef8a277f
Revises: ead705d207f5
Create Date: 2025-03-20 12:14:40.424278

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "68ceef8a277f"
down_revision: Union[str, None] = "ead705d207f5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "channels", sa.Column("channel_auto_caption", sa.Boolean(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("channels", "channel_auto_caption")
    # ### end Alembic commands ###
