"""add_many_to_many_relationship

Revision ID: 60127fabe39c
Revises: 68ceef8a277f
Create Date: 2025-04-02 13:23:47.524372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60127fabe39c'
down_revision: Union[str, None] = '68ceef8a277f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_channels',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.channel_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.telegram_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('channels', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint('channels_admin_id_fkey', 'channels', type_='foreignkey')
    op.drop_column('channels', 'admin_id')
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.add_column('channels', sa.Column('admin_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.create_foreign_key('channels_admin_id_fkey', 'channels', 'users', ['admin_id'], ['telegram_id'], ondelete='CASCADE')
    op.drop_column('channels', 'updated_at')
    op.drop_table('user_channels')
    # ### end Alembic commands ###
